included:
  - Package.swift
  - Examples
  - Sources
  - Tests

excluded:
  - Pods

disabled_rules:
  - file_length
  - type_body_length
  - function_body_length
  - function_parameter_count

opt_in_rules:
  - empty_count
  - comment_spacing
  - force_unwrapping

line_length: 120
