name: Danger

on: 
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Sources/**'
      - 'Examples/**'
      - 'Tests/**'
      - 'Dangerfile.swift'
      - 'Package.swift'
      - '.swiftlint.yml'

concurrency:
  group: danger-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  danger-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
