name: CocoaPods

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0
      - name: Switch Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'
      - name: Deploy to CocoaPods
        run: |
          set -eo pipefail
          export LIB_VERSION=${{ steps.latest_tag.outputs.tag }}
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.PODS_TRUNK_TOKEN }}
