name: Build and Test Swift Package

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Sources/**'
      - 'Examples/**'
      - 'Tests/**'
      - 'Package.swift'

jobs:
  build:
    strategy:
      matrix:
        ios:
          - version: '18.2'
            device: 'iPhone 16'
            xcode: '16.2.0'
      fail-fast: false
    runs-on: macos-15
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Switch Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '${{ matrix.ios.xcode }}'
    - name: Build and Test (iOS ${{ matrix.ios.version }})
      run: xcodebuild build -scheme GreedyKit -destination 'platform=iOS Simulator,OS=${{ matrix.ios.version }},name=${{ matrix.ios.device }}' test | xcbeautify
