name: Build Swift Package

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-old:
    strategy:
      matrix:
        ios:
          - version: '13.7'
            device: 'iPhone 11'
            xcode: '11.7'
          - version: '14.5'
            device: 'iPhone 12 Pro'
            xcode: '12.5.1'
      fail-fast: false
    runs-on: macos-11 
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Switch Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '${{ matrix.ios.xcode }}'
    - name: Build (iOS ${{ matrix.ios.version }})
      run: xcodebuild build -scheme GreedyKit -destination 'platform=iOS Simulator,OS=${{ matrix.ios.version }},name=${{ matrix.ios.device }}'
  build-new:
    strategy:
      matrix:
        ios:
          - version: '15.5'
            device: 'iPhone 13 Pro'
            xcode: '13.4.1'
          - version: '16.0'
            device: 'iPhone 14'
            xcode: '14.0.1'
      fail-fast: false
    runs-on: macos-12
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Switch Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '${{ matrix.ios.xcode }}'
    - name: Build (iOS ${{ matrix.ios.version }})
      run: xcodebuild build -scheme GreedyKit -destination 'platform=iOS Simulator,OS=${{ matrix.ios.version }},name=${{ matrix.ios.device }}'
