name: Build Swift Package

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-old:
    strategy:
      matrix:
        ios:
          - version: '13.7'
            device: 'iPhone 11'
          - version: '14.5'
            device: 'iPhone 12 Pro'
      fail-fast: false
    runs-on: macos-11 
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build (iOS ${{ matrix.ios.version }})
      run: xcodebuild build -scheme GreedyKit -destination 'platform=iOS Simulator,OS=${{ matrix.ios.version }},name=${{ matrix.ios.device }}'
  build-new:
    strategy:
      matrix:
        ios:
          - version: '15.5'
            device: 'iPhone 13 Pro'
          - version: '16.0'
            device: 'iPhone 14'
      fail-fast: false
    runs-on: macos-11 
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build (iOS ${{ matrix.ios.version }})
      run: xcodebuild build -scheme GreedyKit -destination 'platform=iOS Simulator,OS=${{ matrix.ios.version }},name=${{ matrix.ios.device }}'
